version: "3.8"

services:
  excalidraw-storage-backend:
    image: alswl/excalidraw-storage-backend:v2023.11.11
    ports:
      - "3003:80"
    environment:
      STORAGE_URI: redis://redis:6379
      PORT: 80
    networks:
      excalidraw:

  excalidraw-room:
    image: excalidraw/excalidraw-room
    ports:
      - "3002:80"
    environment:
      PORT: 80

  redis:
    image: redis
    networks:
      excalidraw:

networks:
  excalidraw:
